// ErrorCodes.h
#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum ErrorCode {
    SUCCESS = 0,
    SUCCESS_CONNECTED,
    
    INIT_ERROR = 1000,
    
    DISPLAY_ERROR = 2000,
    
    SECRETS_ERROR = 3000,
    CONFIG_FILE_OPEN_READ_ERROR,
    CONFIG_FILE_EXIST_ERROR,
    CONFIG_FILE_OPEN_WRITE_ERROR,
    JSON_PARSE_ERROR,
    SPIFFS_BEGIN_ERRROR,

    WIFI_ERROR = 4000,
    WIFI_CANT_CONNECT,

    STRAVA_ERROR = 5000,
    HTTP_REQUEST_ERROR,
    DESERIALIZE_JSON_ERROR,
    STRAVA_PAYLOAD_ERROR



};

#endif // ERROR_CODES_H
